require("vim._core.ui2").enable({})

require("config.options")
require("config.keymaps")
require("config.commands")
require("config.theme")

require("plugins.mini-icons")
require("plugins.oil")
require("plugins.fzf-lua")
require("plugins.lsp")
require("plugins.lazydev")
require("plugins.blink-cmp")
require("plugins.conform")
require("plugins.gitsigns")
require("plugins.snacks")
require("plugins.ufo")
require("plugins.which-key")
require("plugins.lualine")
require("plugins.tree-sitter")
